### ISSUE TITLE
Supports of Vaadin 14

### ISSUE THREAD

**Issue by gronono** [FlowingCode/FontAwesomeIronIconset#1]
Hello,

Since Vaadin 14, the annotation @HtmlImport does not work any more normal mode (only in compatibility mode).
Extract of the javadoc

> NOTE: this annotation is only useful in compatibility mode and it is ignored in normal mode. In order to use a Polymer template inside a component in Vaadin 14+, JsModule annotation should be used. And to use a css file, CssImport should be used. If you want to be able to use your component in both compatibility mode and normal mode of Vaadin 14+ you need to have @HtmlImport along with @JsModule and/or @CssImport annotations. See Vaadin 14 Migration Guide for more information on how to migrate templates from Polymer 2 to Polymer 3.

Could you upgrade to support both modes in Vaadin 14, please ?
Or is there any kind of workaround ?

Regards,
Arnaud

**Comment by javier-godoy** [comment]
Hello. We are working on a 2.0 version targeting Vaadin 14 in npm mode (it's already on master, and should be released soon). Version 1.0 of the addon can be used in Vaadin 14 with compatibility mode.
