### ISSUE TITLE
Adding font-awesome-iron-iconset makes the UploadHandler component from Viritin disappear from my page.

### ISSUE THREAD

**Issue by jorgheymans** [FlowingCode/FontAwesomeIronIconset#108]
Could it be that these 2 add-ons are conflicting somehow? Initially logged here https://github.com/viritin/flow-viritin/issues/60

**Comment by jorgheymans** [comment]
To reproduce: 
- clone https://github.com/vaadin/skeleton-starter-flow-spring
- Add these dependencies in pom.xml
   ```xml
    <dependency>
      <groupId>in.virit</groupId>
      <artifactId>viritin</artifactId>
      <version>2.8.15</version>
    </dependency>
    <dependency>
      <groupId>com.flowingcode.addons</groupId>
      <artifactId>font-awesome-iron-iconset</artifactId>
      <version>5.2.2</version>
    </dependency>
    ```
- Change `MainView.java` to be just this:

```java
@Route
public class MainView extends VerticalLayout {
    public MainView(@Autowired GreetService service) {

        add(new UploadFileHandler((content, fileName, mimeType) -> {
        }));
    }
```
- `mvn clean spring-boot:run`, you will notice the widget being shown in the view. 
- `mvn com.vaadin:vaadin-maven-plugin:clean-frontend`
- `mvn clean spring-boot:run -Pproduction` and the widget disappears from the view.
- Remove the font-awesome-iron-iconset dependency 
- `mvn com.vaadin:vaadin-maven-plugin:clean-frontend`
- `mvn clean spring-boot:run -Pproduction`, the upload widget appears again.

**Comment by javier-godoy** [comment]
Hello. Which exact version of Vaadin are you using? Is there any error message in the browser console?

**Comment by jorgheymans** [comment]
24.3.10, there are no errors reported in the java console.

**Comment by jorgheymans** [comment]
I have tried older versions (up to 2.8.5) of the `viritin` add-on, but the problem persists. It always works in development mode, but never in production mode. It seems that these 2 add-ons are stepping on each other toes somehow. If there is anything i can do to debug this, happy to help.

**Comment by jorgheymans** [comment]
I just figured out that setting `<optimizeBundle>false</optimizeBundle>` on the vaadin-maven-plugin fixes things. So this is likely a bug in Vaadin and not this plugin.

**Comment by jorgheymans** [comment]
This was fixed in Viritin, so i think the issue can be closed here.

**Comment by javier-godoy** [comment]
Thanks for confirming that this issue has been fixed in Viritin. If you encounter any further issues or have additional questions, please feel free to open a new issue.
