### ISSUE TITLE
Support for V23

### ISSUE THREAD

**Issue by vesanieminen** [FlowingCode/FontAwesomeIronIconset#35]
Currently this addon does not work with V23. Do you have any plans to update this?

**Comment by javier-godoy** [comment]
Hello. The addon is based on IronIcon (which is deprecated), andwe consider it's compatible with Vaadin 23 (https://addonsv23-staging.flowingcode.com/font-awesome-iron-iconset uses Vaadin 23.0.8). Maybe the application is missing some `@Uses` or whitelisting of the component. Can you share an example that reproduce the observed issue?

(We are also considering a migration from IronIcon to vaadin icon)

**Comment by vesanieminen** [comment]
@javier-godoy here's the example application I tried this with earlier: https://github.com/vesanieminen/v23-fontawesome-test
I did add the `@Uses` annotations for both icons I'm using there but couldn't figure out how something should be whitelisted.

The app looks like this when I try to run it:

<img width="432" alt="Screenshot 2022-05-10 at 12 12 26" src="https://user-images.githubusercontent.com/108755/167593569-0b29851a-cae7-43d5-95d4-f40fcc822396.png">

**Comment by javier-godoy** [comment]
You need to add `com.flowingcode` to the whitelist in `src/main/resources/application.properties`
```
vaadin.whitelisted-packages = com.vaadin,org.vaadin,dev.hilla,com.example.application,com.flowingcode
```
![image](https://user-images.githubusercontent.com/11554739/167681926-97e882ce-d23a-4952-8189-a97daf9b1723.png)

**Comment by javier-godoy** [comment]
Version 4.0.0 of this addon is compatible with Vaadin 23. Older versions should be compatible with Vaadin 14 up to 23.
