### ISSUE TITLE
Externalize code generator

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/FontAwesomeIronIconset#7]
The code generator for this addon is basically a copy of the code generator in https://github.com/FlowingCode/IronIconsAddon
(modulo some minor differences). Since the generator itself isn't part of the released artifact, and has its own POM, it should be possible to externalize it as an artifact shared by both iron-icons and font-awesom-iron-iconset.

**Comment by mlopezFC** [comment]
Totally agree with this.

**Comment by javier-godoy** [comment]
Now that `@polymer/iron-icons` is dead, there is no need to maintain its code generator (also, the code generator for FontAwesome has evolved and it's a little bit more different than that of IronIconAddon, in comparison with the situation 2 years ago). I would close this issue as wontfix.

**Comment by mlopezFC** [comment]
Agree
