### ISSUE TITLE
FontAwesome add-ons update

### ISSUE THREAD

**Issue by Richard1992** [FlowingCode/FontAwesomeIronIconset#88]
Good night

Equipment

I would like to tell you that I am recently using one of your FontAwesome libraries from a vaadin 24 project, but I have noticed that the icons have an old version, for which I create this issue to update the version of this library if possible.

I am currently using Expert Chat and they tell me that the version they have of fontawesome is 6.1.2 and they are already on 6.4.0.

https://vaadin.com/directory/component/fontawesome-iron-iconset

https://fontawesome.com/versions

Thank you so much

I'll look forward for your answer.

**Comment by javier-godoy** [comment]
Hello. I've updated the add-on to FontAwesome 6.4.0 (#86, #87). We'll release it soon.

**Comment by paodb** [comment]
Hello. We've just released version [5.2.0](https://github.com/FlowingCode/FontAwesomeIronIconset/releases/tag/font-awesome-iron-iconset-5.2.0) which contains the upgrade.

**Comment by Richard1992** [comment]
Hello

Thank you very much for the update but I don't see the POM.xml to add it to my project.

**Comment by javier-godoy** [comment]
Hello. That's right. It seems the POM was not deployed to Vaadin directory. We'll investigate

![image](https://github.com/FlowingCode/FontAwesomeIronIconset/assets/11554739/04febab8-30c0-4a26-aed1-0061801214d8)
